version: '3.8'

services:
  my-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=<MINIO_ACCESS_KEY>
      - MINIO_SECRET_KEY=<MINIO_SECRET_KEY>
      - DESTINATION__FILESYSTEM__CREDENTIALS__ENDPOINT_URL=http://minio:9000
      - DESTINATION__FILESYSTEM__CREDENTIALS__AWS_ACCESS_KEY_ID=<MINIO_ACCESS_KEY>
      - DESTINATION__FILESYSTEM__CREDENTIALS__AWS_SECRET_ACCESS_KEY=<MINIO_SECRET_KEY>


  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: <MINIO_ACCESS_KEY>
      MINIO_SECRET_KEY: <MINIO_SECRET_KEY>
    volumes:
      - minio-data:/data
    command:
      - server
      - /data

volumes:
  minio-data: